baseURL = "http://example.org/"
languageCode = "en-us"
title = "Accessible Minimalism"
theme = "accessible-minimalism"
disableHugoGeneratorInject = true
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

[params]
	author = "John Smith"
	email = "john@example.org"
	emailText = "Email"
	rssText = "RSS feed"

	[[params.socials]]
		url = "http://example.com"
		text = "Social Media"
	[[params.socials]]
		url = "http://example.com"
		text = "Video Series"

